site_name: Илья Кабанов

theme:
    name: 'material'
    features:
      - navigation.indexes
    logo: images/logo.svg
    palette:

    # Light mode
    - media: "(prefers-color-scheme: white)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Тёмная тема

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: gray
      toggle:
        icon: material/toggle-switch
        name: Светлая тема

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - blog:
    - blog_dir: Journal
    - post_dir: Journal/Notes
    - blog_toc: true
  - roamlinks

nav: 
  - Превью: Preview.md
  - Инструкция по блогу: Guide.md
  - Резюме: Resume.md
  - Журнал:
    - Journal/index.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
